name: Secrets scan

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Secrets scan using Gitleaks
      uses: zricethezav/gitleaks-action@master
